# GET http://localhost:4004/odata/v4/my/Colleagues
# Accept: application/json

# GET http://localhost:4004/odata/v4/my/Colleagues(colleague_id='ca93ab7f-ea31-4f99-a4b9-a24fc88b00ae')
# Accept: application/json

# POST http://localhost:4004/odata/v4/my/Colleagues
# Content-Type: application/json
# Accept: application/json

# {
#   "first_name": "Jane",
#   "last_name": "Doe",
#   "email": "jane.doe@example.com",
#   "phone_number": "+31687654321",
#   "last_time_called": "2024-03-05T10:30:00Z",
#   "frequency_level": "High",
#   "status": "Available"
# }


# PATCH http://localhost:4004/odata/v4/my/Colleagues/ca93ab7f-ea31-4f99-a4b9-a24fc88b00ae
# Content-Type: application/json
# Accept: application/json

# {
#   "status": "Busy",
#   "frequency_level": "Low"
# }


DELETE http://localhost:4004/odata/v4/my/Colleagues/9aeb0510-f037-4e4b-8978-544fc830831d
Content-Type: application/json
Accept: application/json
